include:
  - project: 'katagena/templates'
    file: 'ci/global.yml'

build:
  stage: build
  image: node:latest
  script:
    - apt-get update
    - apt-get install -y make
    - make publish
    - ls -al public/
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
