include:
  - template: Auto-DevOps.gitlab-ci.yml

pages:
  stage: build
  image: nouchka/japromis:latest
  script:
    - mkdir public/
    - cp /usr/share/nginx/html/index.html public/index.html
    - cp /usr/share/nginx/html/fr.html public/fr.html
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
