include:
  - project: 'katagena/templates'
    file: 'ci/global.yml'

build:
  stage: build
  image: node:latest
  script:
    - apt-get update
    - apt-get install -y make
    - make publish
    - mkdir public/
    - cp /usr/share/nginx/html/index.html public/index.html
    - cp /usr/share/nginx/html/fr.html public/fr.html
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
