include:
  - project: 'katagena/templates'
    file: 'ci/global.yml'

variables:
  EMAIL: "ja.promis@katagena.com"
  PHONE: "0102030405"
  ADDRESS: "Bergerac"
  OUTPUT_TEMPLATE: "kendall"
  TEMPLATE_GIT: "https://github.com/nouchka/jsonresume-theme-kendall.git"
  RESUME_FILE: "fr.json"

generate-resume:
  stage: build
  image:
    name: nouchka/hackmyresume
    entrypoint: [""]
  script:
    - mkdir -p public/ pdf/
    - cp favicon.ico public/
    - /start.sh
    - ls -al
    - cp index.html public/
    - cp index.pdf pdf/japromis-cv.pdf
    - export RESUME_FILE=resume.json
    - /start.sh
    - ls -al
    - cp index.pdf pdf/japromis-resume.pdf
  artifacts:
    paths:
    - public
    - pdf
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
