include:
  - project: 'katagena/projects'
    ref: master
    file: 'playbooks/roles/templating/templates/generic/gitlabci.auto-devops'

pages:
  stage: build
  image: nouchka/japromis:latest
  script:
    - mkdir public/
    - cp /usr/share/nginx/html/index.html public/index.html
    - cp /usr/share/nginx/html/fr.html public/fr.html
  artifacts:
    paths:
    - public
  only:
  - master

