hackmyresume:
  image: nouchka/hackmyresume
  environment:
    - OUTPUT_TEMPLATE=onepage
    - DISPLAY=unix$DISPLAY
  env_file:
    - .env
  volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix
    - /tmp/resume:/usr/share/nginx/html
